### ISSUE TITLE
Add checksum release artifacts

### ISSUE THREAD

**Issue by taqtiqa-mark** [zombiezen/redo-rs#15]
Would you accept a PR to this effect?

Edit: Initially SHA256, others can be added as required.

**Comment by zombiezen** [comment]
Can you help me understand the use case here? I'm assuming the SHA256 checksum would be provided alongside the other assets, which already use HTTPS to ensure integrity.

**Comment by taqtiqa-mark** [comment]
> Can you help me understand the use case here?

Sure. Installation/provisioning scripts (Chef, Puppet, Salt, etc) that use such values to validate downloaded artifacts before installing/updating them.

**Comment by zombiezen** [comment]
Can't the appropriate hashes be generated by downloading the artifact while developing the script and generating the hash then? My concern is maintaining the set of algorithms that people want hashes for.

To be clear, I understand the need for distributing checksums for larger projects where the release is served from a different domain that the rest of the project (i.e. mirrors). However, that's not the case here (yet).

**Comment by taqtiqa-mark** [comment]
>Can't the appropriate hashes be generated by downloading the artifact....

This is a chicken-egg problem.

> My concern is maintaining the set of algorithms that people want hashes for.

Agreed.  These generally are one-off CI/CD steps.  Generally its not a maintenance burden once setup.   

This is more a 'will you accept such a PR' rather than 'please can you implement such a PR'

> To be clear, I understand the need for distributing checksums for larger projects where the release is served from a different domain that the rest of the project (i.e. mirrors).

Not sure I follow.
The issue is providing automated install script authors with an 'authoritative' checksum/hash - Yes, workarounds are possible.
