### ISSUE TITLE
RUSTSEC-2020-0014

### ISSUE THREAD

**Issue by taqtiqa-mark** [zombiezen/redo-rs#18]
Initial (development) run of security audit [results](https://github.com/taqtiqa-mark/redo-rs/runs/4973406088?check_suite_focus=true):

[RUSTSEC-2020-0014](https://rustsec.org/advisories/RUSTSEC-2020-0014.html)

**Comment by zombiezen** [comment]
This program's usage of SQLite is fairly limited, and AFAICT don't use any of the affected APIs.
