### ISSUE TITLE
BATS integration tests

### ISSUE THREAD

**Issue by taqtiqa-mark** [zombiezen/redo-rs#24]
Before sinking time in to a PR that gets rejected... 

The proposal is to to use [bats](https://bats-core.readthedocs.io/en/stable) to provide integration tests in the form of the upstream cookbook examples.

````bash
@test "invoking redo with hello" {
  run redo hello
  [ "$status" -eq 0 ]
  [ "$output" = "redo  hello" ]
  [ "$BATS_RUN_COMMAND" = "redo  hello" ]
}
````

More complex integration [tests are possible](https://bats-core.readthedocs.io/en/stable/writing-tests.html)

Shell scripts provide a way to integrate `redo` into the build/test scaffolding of a crate, and shell scripts are an alternative to a Rust based inventory/catalogue approach - see PR #22 for the Rust inventory/catalogue based approach. 

Both approaches have their strengths/weaknesses, but essentially they address distinct use case for `redo`.

**Comment by zombiezen** [comment]
I don't see an advantage over the approach in tests/integration.rs. It's introducing a new domain-specific language, which is higher maintenance than using shell or Rust.
